on:
  push:
    branches: [main, staging]
  pull_request:
    branches: [main, staging]

name: R-Package

jobs:
  R-Package:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: windows-latest, r: "release" }
          - { os: macos-latest, r: "release" }
          - { os: ubuntu-latest, r: "release" }

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      USERNAME: ${{ secrets.USERNAME}}
      ENVIRONMENT: "ci"

    steps:
      - name: Checkout Code Base
        uses: actions/checkout@v3

      - name: Set up R Environment
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - name: Install Dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - name: Create and Populate .Renviron file
        run: |
          echo Username="$USERNAME" >> ~/.Renviron
        shell: bash

      - name: Run Unit Tests
        uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
